language: C
sudo: enabled
script: ./.travis.sh

before_install:
  - wget https://github.com/phorward/phorward/archive/v0.23.0.tar.gz
  - tar xvfz v0.23.0.tar.gz
  - pushd phorward-0.23.0 && ./configure --prefix=/usr && make && sudo make install && popd
  - touch *
 
